Repository SamSam-kakotechboot/travel_BE, pull requests merged in 2024-08, with the labels that each got.

#4 엔티티 클래스 생성
  build.gradle
  src/main/java/com/samsam/travel/travelcommerce/dao/Cart.java
  src/main/java/com/samsam/travel/travelcommerce/dao/Orders.java
  src/main/java/com/samsam/travel/travelcommerce/dao/Review.java
  src/main/java/com/samsam/travel/travelcommerce/dao/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/dao/User.java
Labels: 💡 기능 개발, 🗃️ 프로젝트 구조 및 환경 설정

#14 초기 Utils 클래스 생성 및 테스트
  build.gradle
  src/main/java/com/samsam/travel/travelcommerce/utils/Common.java
  src/main/java/com/samsam/travel/travelcommerce/utils/ReturnMessage.java
  src/test/java/com/samsam/travel/travelcommerce/TravelUtilsTests.java
Labels: 💡 기능 개발, 🗃️ 프로젝트 구조 및 환경 설정

#16 상품 등록 api 구현(임시)
  src/main/java/com/samsam/travel/travelcommerce/dao/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/TicketAddDto.java
Labels: ⚙️ 리팩토링, 💡 기능 개발

#21 이그노어 파일 수정 및 초기 데이터 sql 파일 생성
  .gitignore
  src/main/resources/migration/20240804_insert_init_data.sql
Labels: 📝 문서화

#23 refactor: dao 디렉토리명을 entity로 변경
  src/main/java/com/samsam/travel/travelcommerce/dao/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/entity/Cart.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Orders.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Review.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/entity/User.java
Labels: ⚙️ 리팩토링

#22 상품 수정 api 구현 및 상품 dto 구조 변경
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketAddDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketModifyDto.java
Labels: ⚙️ 리팩토링, 💡 기능 개발

#24 Global exception handler 추가
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/global/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/global/error/ErrorResponse.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/GlobalExceptionHandler.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/BusinessException.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/ErrorCode.java
Labels: 💡 기능 개발

#26 Spring Security 설정
  build.gradle
  src/main/java/com/samsam/travel/travelcommerce/domain/user/repository/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/user/repository/UserRepository.java
  src/main/java/com/samsam/travel/travelcommerce/entity/model/Role.java
  src/main/java/com/samsam/travel/travelcommerce/security/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/security/auth/AuthToken.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/AuthTokenProvider.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/jwt/CustomPasswordAuthenticationManager.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/jwt/CustomPasswordAuthenticationToken.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/jwt/JwtAuthToken.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/jwt/JwtAuthTokenProvider.java
  src/main/java/com/samsam/travel/travelcommerce/security/auth/jwt/JwtFilter.java
  src/main/java/com/samsam/travel/travelcommerce/security/config/SecurityConfig.java
  src/main/java/com/samsam/travel/travelcommerce/security/error/exception/JwtTokenException.java
  src/main/java/com/samsam/travel/travelcommerce/security/error/handler/JwtExceptionFilter.java
  src/main/resources/application.yml
Labels: 🗃️ 프로젝트 구조 및 환경 설정

#29 회원 본인 정보 조회 api 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/user/api/UserController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/service/UserService.java
  src/main/java/com/samsam/travel/travelcommerce/dto/user/UserInfoResponse.java
  src/main/java/com/samsam/travel/travelcommerce/entity/User.java
Labels: 💡 기능 개발

#31 Ticket 리팩토링
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketModifyDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketResponseDto.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
Labels: ⚙️ 리팩토링

#33 CommonCode 주석 수정
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
Labels: ⚙️ 리팩토링

#32 관리자: 유저 권한 부여 기능 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/user/api/AdminController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/repository/UserRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/service/AdminService.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/test/java/com/samsam/travel/travelcommerce/AdminServiceTest.java
Labels: 💡 기능 개발

#36 응답 생성 로직의 중복을 제거를 위해 ResponseUtil 도입
  src/main/java/com/samsam/travel/travelcommerce/domain/user/api/AdminController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/api/AuthController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/api/UserController.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/utils/ResponseUtil.java
Labels: ⚙️ 리팩토링

#38 [상품] 삭제 기능 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
Labels: 💡 기능 개발

#39 일반 회원: 주문 요청 기능 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/OrderController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/repository/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/order/repository/OrderRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/OrderService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/repository/UserRepository.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderDetail.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderRequest.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Orders.java
  src/main/java/com/samsam/travel/travelcommerce/entity/model/OrderStatus.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/TicketNotFoundException.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/ErrorCode.java
  src/test/java/com/samsam/travel/travelcommerce/OrderServiceTest.java
Labels: 💡 기능 개발

#41 장바구니 기능 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/cart/api/CartController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/cart/repository/CartRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/cart/service/CartService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/cart/service/CartServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/cart/CartAddDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/cart/CartDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketResponseDto.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Cart.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/CartInvalidInputException.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/ErrorCode.java
  src/main/resources/migration/20240731_create_init_table.sql
Labels: 💡 기능 개발

#42 일반 회원: 주문 리스트 조회 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/OrderController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/repository/OrderRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/OrderService.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderListResponse.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Orders.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
Labels: 💡 기능 개발

#43 일반 회원: 주문 취소 기능 구현
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/OrderController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/OrderService.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/ResourceNotFoundException.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/ErrorCode.java
Labels: 💡 기능 개발

#45 [리뷰] api 명세서에 따른 기능 구현 완료
  src/main/java/com/samsam/travel/travelcommerce/domain/review/api/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/review/api/ReviewController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/repository/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/review/repository/ReviewRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/.gitkeep
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/ReviewService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/review/ReviewAddDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/review/ReviewDto.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Review.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Ticket.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/ReviewDuplicatedException.java
  src/main/java/com/samsam/travel/travelcommerce/global/error/exception/ReviewInvalidInputException.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/CommonCode.java
  src/main/java/com/samsam/travel/travelcommerce/global/status/ErrorCode.java
  src/main/java/com/samsam/travel/travelcommerce/security/config/SecurityConfig.java
  src/main/resources/migration/20240809_alter_review_table.sql
Labels: 💡 기능 개발

#46 Ticket Exception 부분 수정
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
Labels: ⚙️ 리팩토링

#48 Origin/feature/cors
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/OrderController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/OrderService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/api/ReviewController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/repository/ReviewRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/ReviewService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/repository/UserRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/user/service/UserAuthService.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderDetail.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderListResponse.java
  src/main/java/com/samsam/travel/travelcommerce/dto/order/OrderRequest.java
  src/main/java/com/samsam/travel/travelcommerce/dto/review/ReviewAddDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketResponseDto.java
  src/main/java/com/samsam/travel/travelcommerce/dto/user/LoginRequest.java
  src/main/java/com/samsam/travel/travelcommerce/dto/user/LoginResponse.java
  src/main/java/com/samsam/travel/travelcommerce/dto/user/SignUpRequest.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Orders.java
  src/main/java/com/samsam/travel/travelcommerce/entity/Review.java
  src/main/resources/application.yml
  src/main/resources/migration/20240804_insert_init_data.sql
  src/main/resources/migration/20240813_insert_test_data.sql
  src/main/resources/migration/20240817_alter_init_table.sql
Labels: ⚙️ 리팩토링, 💡 기능 개발, 🗃️ 프로젝트 구조 및 환경 설정

#49 Origin/feature/image
  src/main.zip
  src/main/java/com/samsam/travel/travelcommerce/domain/image/api/ImageController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/image/service/ImageService.java
  src/main/java/com/samsam/travel/travelcommerce/security/config/SecurityConfig.java
  src/main/resources/image/ticket/Busch Gardens.png
  src/main/resources/image/ticket/Disneyland.png
  src/main/resources/image/ticket/Europa Park.png
  src/main/resources/image/ticket/Everland.png
  src/main/resources/image/ticket/Fuji-Q Highland.png
  src/main/resources/image/ticket/Gardaland.png
  src/main/resources/image/ticket/Legoland.png
  src/main/resources/image/ticket/Lotte World.png
  src/main/resources/image/ticket/Ocean Park.png
  src/main/resources/image/ticket/PortAventura.png
  src/main/resources/image/ticket/SeaWorld.png
  src/main/resources/image/ticket/Six Flags Magic Mountain.png
  src/main/resources/image/ticket/Tokyo Disneyland.png
  src/main/resources/image/ticket/Universal Studios.png
Labels: 💡 기능 개발, 🗃️ 프로젝트 구조 및 환경 설정

#50 Origin/feature/review-delete
  src/main/java/com/samsam/travel/travelcommerce/domain/image/api/ImageController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/image/service/ImageService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/api/ReviewController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/repository/ReviewRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/api/TicketController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/service/TicketServiceImpl.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketSearchResultDto.java
  src/main/resources/image/review/REVIEW-CBF24FAC-0BB4-4ECC-A103-E6E317D9458C.png
  src/main/resources/image/review/REVIEW-D5CD00F5-0008-4989-A9A4-FEEAAC7CFBBE.png
Labels: ⚙️ 리팩토링, 💡 기능 개발, 🎨 디자인, 🗃️ 프로젝트 구조 및 환경 설정

#51 Origin/feature/ai sentence
  src/main.zip
  src/main/java/com/samsam/travel/travelcommerce/domain/image/api/ImageController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/image/service/ImageService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/api/OrderController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/repository/OrderRepository.java
  src/main/java/com/samsam/travel/travelcommerce/domain/order/service/OrderService.java
  src/main/java/com/samsam/travel/travelcommerce/domain/review/api/ReviewController.java
  src/main/java/com/samsam/travel/travelcommerce/domain/ticket/repository/TicketRepository.java
  src/main/java/com/samsam/travel/travelcommerce/dto/ticket/TicketResponseDto.java
  src/main/resources/image/review/REVIEW-205F1B42-240F-4BFD-BEBB-15E07E58B38B.png
  src/main/resources/image/ticket/강릉 아르떼뮤지엄.png
  src/main/resources/image/ticket/강화 루지.png
  src/main/resources/image/ticket/과천 서울랜드.png
  src/main/resources/image/ticket/서울 롯데월드 타워 전망대.png
  src/main/resources/image/ticket/서울 롯데월드.png
  src/main/resources/image/ticket/서울 여의도 크루즈.png
  src/main/resources/image/ticket/용인 민속촌.png
  src/main/resources/image/ticket/용인 에버랜드.png
  src/main/resources/image/ticket/용인 캐리비안 베이.png
  src/main/resources/image/ticket/제주 아르떼뮤지엄.png
  src/main/resources/image/ticket/제주 아쿠아플래닛.png
  src/main/resources/image/ticket/제주 에코랜드.png
  src/main/resources/image/ticket/제주 투어패스.png
  src/main/resources/migration/20240823_ticket_insert_table.sql
  src/main/resources/migration/20240828_cart_truncate_table.sql
Labels: ⚙️ 리팩토링, 💡 기능 개발, 🎨 디자인
